name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  test:
    name: Laravel ${{ matrix.laravel }} - PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [9.*, 10.*, 11.*, 12.*]
        exclude:
          # Laravel 9 requires PHP < 8.3
          - laravel: 9.*
            php: 8.3
          - laravel: 9.*
            php: 8.4
          # Laravel 11 requires PHP >= 8.2
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, json
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit